[RFC] Development docs: add commit message conventions
xcp-ng/xcp-ng-org pull request #117
Opened 2021-07-30 16:55 UTC by stormi

Do not merge yet: it's a support for discussion with every developer involved.

2021-08-24 08:52 UTC, benjamreis approved these changes
LGTM :)
Not fund of 70 char tops for a line but I can live with it!

2021-09-23 08:28 UTC, pdonias requested changes

2021-09-23 10:54 UTC, stormi commented on docs/develprocess.md
> +* Is it a feature, a bugfix, a security fix (*type*)?
```suggestion
* Is it a feature, a bugfix, a security fix, a refactoring, a documentation update, etc. (*type*)?
```

2021-09-23 11:05 UTC, stormi commented on docs/develprocess.md
> +* (`Closes: ...`)
Because of the warning below saying that it's not suitable to every project, as some may want to close issues manually.

2021-09-23 11:08 UTC, stormi commented on docs/develprocess.md
> +As a member of the Linux Foundation, XCP-ng asks every contributor to testify that they are allowed to contribute the code or documentation they submit to us. See <https://wiki.linuxfoundation.org/dc
```suggestion
As a member of the Linux Foundation, XCP-ng asks every contributor to certify that they are allowed to contribute the code or documentation they submit to us. See <contributing.md#developer-certificate-of-origin-dco> for details. This is enforced for every repository under the GitHub `xcp-ng` and `xcp-ng-rpms` organizations.
```

2021-09-23 11:22 UTC, stormi commented
The failing DCO check will be fixed once I squash the commits before the merge.

2021-09-29 07:59 UTC, julien-f approved these changes
Nothing to add, good work :-)

2021-09-29 09:40 UTC, Wescoeur approved these changes

2021-09-29 15:14 UTC, beshleman approved these changes

2021-09-30 11:20 UTC, merged