Update Reset Root Password to match the latest Citrix Doc
xcp-ng/xcp-ng-org pull request #143
Opened 2021-11-05 10:36 UTC by ManonMercier

Signed-off-by: Manon Mercier <manon.mercier@vates.fr>

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://xcp-ng.org/docs/contributing.html#developer-certificate-of-origin-dco

2021-11-05 10:43 UTC, olivierlambert requested changes

2021-11-05 10:43 UTC, olivierlambert commented on docs/troubleshooting.md
> +Hi, this is a small trick I had to use once [(original article)](https://support.citrix.com/article/CTX214360)
We can probably rephrase this to be a bit more formal. Explaining the context, something like "If you need to reset your XCP-ng root password, you can follow this procedure".

2021-11-05 10:43 UTC, olivierlambert commented on docs/troubleshooting.md
> +* Select XCP-ng boot menu entry and press **e** key to edit boot options.
Instead of **e** to emphasis on the key, we could use `e` instead.

2021-11-05 10:43 UTC, olivierlambert commented on docs/troubleshooting.md
> +* Locate read-only parameter **ro** and replace it with **rw init=/sysroot/bin/sh**.
Same comment apply, replace all Markdown bold by code style (using backticks)

2021-11-05 10:45 UTC, olivierlambert commented
Don't close the PR ;) You can make modification and re-push your code, this will solve the comments.

2021-11-05 10:54 UTC, stormi commented
Closing the PR was needed to fix the DCO (they did not want to use git, but I think they'll need to in the end)

2021-11-05 11:01 UTC, stormi commented
I fixed the DCO. @ManonMercier you can now handle the comments in a new commit (don't forget the DCO for that commit of course).

2021-11-23 12:30 UTC, olivierlambert approved these changes
Nice catch about the <kbd> thing, I wasn't aware of this!

2021-11-23 12:30 UTC, merged

2021-11-23 12:46 UTC, stormi commented on docs/troubleshooting.md
> +If you need to modify your XCP-ng root password, you may follow the steps below. The full prodecure can also be found on [this page](https://support.citrix.com/article/CTX214360).
What's a prodecure ? :D