Added some details on checking IOMMU for PCI passthrough
xcp-ng/xcp-ng-org pull request #230
Opened 2023-03-18 10:40 UTC by alfh

Add info on how to check if IOMMU is enabled on the current running kernel, and how to add the kernel parameters. Also add some info related to iommu_groups, and hint on iommu=pt for performance.

I used this to enable PCI passthrough of USB controller, which worked, even if I did not have anything in the /sys/kernel/iommu_groups.

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [ x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [ x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://xcp-ng.org/docs/contributing.html#developer-certificate-of-origin-dco

2023-03-20 12:17 UTC, andSmv reviewed
The dom0 kernel doesn't have to access the platform IOMMU(s). The IOMMU need to be enabled on the platform in the firmware (BIOS/UEFI), but it is managed by XEN and in totally transparent manner to the VMs.  So this is true for PCI passthrough needs. However, there are some patches in XCP-ng,  which under some circumstances enable such an access for the VMs. But this can be veiwed as a very basic paravartualized IOMMU (and which is not pluged to Linux kernel IOMMU framework) . This pv IOMMU is not discovered through Intel DMAR (or AMD IVRS) ACPI tables. To be honest, this facility is almost never used.  So, in any circumstances, you don't have to manipulate dom0 kernel command line IOMMU-related parameters.

2023-08-25 11:39 UTC, stormi requested changes
Marking as "changes requested" so that we don't merge by mistake.

2026-01-12 10:10 UTC, TSnake41 commented
You are unlikely to detect a working DMAR in Dom0; and intel_iommu has no effect on Xen. If the IOMMU is enabled in the system, it is automatically available for use (and used).

Actually, Xen provides a fairly easy way to check for PCI Passthrough support, you just need to check for `hvm_directio` in `virt_caps` of `xl info`. If you see it; that means you have PCI Passthrough supported.

2026-06-24 22:47 UTC, stormi commented
There are multiple comments on the PR, without answers. @alfh do you intend to finalize this PR?

2026-06-25 18:12 UTC, alfh commented
No, I'm no longer trying to get this to work, so I will just abandon and close this PR.

2026-06-25 18:12 UTC, closed without merging