Add new blog post related to XCP-NG and template
xcp-ng/xcp-ng-org pull request #276
Opened 2024-07-15 09:39 UTC by mickaelbaron

Hi,

Please find in this PR, a contribution to add a new blog post related to XCP-NG and how to create and use custom XCP-NG templates.

Best

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://docs.xcp-ng.org/project/contributing/#developer-certificate-of-origin-dco

2024-07-15 09:42 UTC, olivierlambert commented
Thanks @mickaelbaron 

Putting this to review :+1:

2024-07-15 09:48 UTC, olivierlambert commented
Also @Danp2 can help to review :)

2024-07-16 08:59 UTC, Fohdeesha reviewed
due to family issues I have no time to review documentation currently

2024-07-16 09:44 UTC, olivierlambert commented
No worries, Dan will do it :+1:

2024-07-20 23:06 UTC, Danp2 requested changes

2024-07-21 10:13 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +How to create and use custom XCP-NG templates: a guide for Ubuntu?
I followed the questions (description) used in other guides. https://docs.xcp-ng.org/category/guides/

I propose this update: How to create and use custom XCP-NG templates for Ubuntu?

2024-07-21 10:17 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +This post explains in detail the steps to create templates based on Ubuntu. The same principles apply to other Linux distributions, provided they support [Cloud-init](https://cloud-init.io/). We will
I meant that what I demonstrate can also be applied to other distributions like Debian, for example as long as Cloud-init is supported

2024-07-21 10:51 UTC, Danp2 commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +This post explains in detail the steps to create templates based on Ubuntu. The same principles apply to other Linux distributions, provided they support [Cloud-init](https://cloud-init.io/). We will
I was only questioning the repeated linking to external sites for things like Cloud-init. Should all instances be links or only the first one? @olivierlambert Is there a preference here?

2024-07-21 11:14 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* system configuration (e.g., hostname).
Oki

2024-07-21 11:15 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* [Xen Orchestra](https://xen-orchestra.com) from the sources or Xen Orchestra virtual Applicance (XOA)
Ok

2024-07-21 11:16 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +
Ok, thanks

2024-07-21 11:27 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +This post explains in detail the steps to create templates based on Ubuntu. The same principles apply to other Linux distributions, provided they support [Cloud-init](https://cloud-init.io/). We will
Sorry, I used to use links for each time I mention a tool (if link is existing).

2024-07-21 11:32 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +
I used a "full" impersonal structure

In order to access the ISO file during the virtual machine creation step, it needs to be placed in an ISO storage repository. There are several types available (Local, NFS, or SMB). For this post, the first type will be used. Feel free to browse through this [post](https://xcp-ng.org/blog/2022/05/05/how-to-create-a-local-iso-repository-in-xcp-ng/) to learn how to create a local ISO storage repository. In the following, I assume that there is a local ISO storage repository on the XCP-NG host.

2024-07-21 11:45 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Drag and drop or select the file *ubuntu-22.04.4-live-server-amd64.iso*, click on **Import**, and wait for the import to finish.
To be honest, I do not use this solution. I upload the ISO file by scp.

However, I will take your comment into account.

2024-07-21 11:46 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +> You can also directly upload the ISO file to the server where the local storage is located using the **scp** tool.
Ok

2024-07-21 17:31 UTC, olivierlambert commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +This post explains in detail the steps to create templates based on Ubuntu. The same principles apply to other Linux distributions, provided they support [Cloud-init](https://cloud-init.io/). We will
I think it's a detail we can ignore

2024-07-21 22:09 UTC, Danp2 requested changes

2024-07-22 08:42 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Select the Ubuntu Focal Fossa 22.04 template (which is more of a loading profile than a template) and enter the following values for the parameters: custom-ubuntu22.04 for the name, 1 CPU, 4 GB of
Oops, big mistake, sorry and thank you. It will be fixed in the next commit.

2024-07-22 08:45 UTC, olivierlambert commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Select the Ubuntu Focal Fossa 22.04 template (which is more of a loading profile than a template) and enter the following values for the parameters: custom-ubuntu22.04 for the name, 1 CPU, 4 GB of
Don't worry, reviews are meant for this.

2024-07-25 12:03 UTC, MrGrymReaper commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Select the Ubuntu Focal Fossa 22.04 template (which is more of a loading profile than a template) and enter the following values for the parameters: custom-ubuntu22.04 for the name, 1 CPU, 4 GB of
> I've also experimented with Ubuntu 24.04. I suppose it was a bad copy/paste.

When you originally wrote the text you copy and pasted Focal Fossa release code name of Ubuntu 20.04, Jammy Jellyfish is the release code name of 22.04 and the code name for 24.04 is Noble Numbat. FYI

2024-07-25 12:45 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Select the Ubuntu Focal Fossa 22.04 template (which is more of a loading profile than a template) and enter the following values for the parameters: custom-ubuntu22.04 for the name, 1 CPU, 4 GB of
Damn, I'm lost with these code names, I shouldn't have specified it because it induces errors and nobody cares.

2024-07-25 14:57 UTC, MrGrymReaper requested changes
There really needs to specify that the release is an LTS release of Ubuntu being used as part of this guide. This is especially important for if the system requirements change in later releases, as well as package names change in relation to this guide.

The LTS releases of Ubuntu are supported for a longer period of time in relation to the standard support releases. This thus means that the package names tend to be fairly set during that time and don't change often.

Between standard supported releases the package names can change more often. Also the standard supported releases of Ubuntu have the latest versions of software, while the LTS are an older more stable production test long term supported version.

So any commands required may not work between releases or can be different.

2024-07-29 15:16 UTC, stormi commented
Should this be a guide inside Xen Orchestra's documentation instead? These templates are not directly an XCP-ng feature.

2024-07-29 15:23 UTC, olivierlambert commented
> Should this be a guide inside Xen Orchestra's documentation instead? These templates are not directly an XCP-ng feature.

Sometimes it's hard to find the right place between both. Frankly, at some point, a unified doc would make more sense. But until then, I think that would be OK to get this one into XCP-ng doc.

2024-08-19 08:38 UTC, mickaelbaron commented on docs/guides/create-use-custom-xcpng-ubuntu-templates.md
> +* Select the Ubuntu Focal Fossa 22.04 template (which is more of a loading profile than a template) and enter the following values for the parameters: custom-ubuntu22.04 for the name, 1 CPU, 4 GB of
Hi,

I updated the documentation to fix this problem.

Mickael

2024-10-03 20:20 UTC, mickaelbaron commented
Hello,

What’s the status of my pull request?

2024-10-11 09:29 UTC, mickaelbaron commented
Hi,

I would like to know if my PR is still relevant

Best

2024-10-11 10:14 UTC, stormi commented
I think so, based on @olivierlambert's comments.

2024-10-11 10:39 UTC, olivierlambert commented
Sorry for being very late on this, we were under too much water. Merging it ASAP.

2024-10-11 10:39 UTC, olivierlambert approved these changes

2024-10-11 10:44 UTC, olivierlambert commented
@stormi I don't know why there's a review stuck while it was answered and why the DCO isn't correctly checked? :thinking:

2024-10-11 10:49 UTC, stormi commented
The PR doesn't look in a good state, from the git point of view. Too many commits in the branch, which should likely be rebased on master, and not contain a merge commit like it does now.

2024-10-11 10:49 UTC, stormi commented
I don't understand @Danp2's merge commit :thinking:

2024-10-11 10:50 UTC, stormi commented
I'll try to fix it.

2024-10-11 10:56 UTC, stormi commented
(Ideally, @Danp2 should review the changes made after his comments and Approve the PR)

2024-10-11 10:58 UTC, closed without merging

2024-10-11 10:59 UTC, stormi commented
I don't know why it closed the PR after my force-push to remove the merge commit.

2024-10-11 11:02 UTC, stormi commented
Looks like there's something I don't understand in how github works with forks and pushes to PRs. I'll create a new PR with these changes.