Added Fibre Channel (FC) to list of supported storage types
xcp-ng/xcp-ng-org pull request #293
Opened 2024-11-04 15:01 UTC by thomas-dkmt

As requested by Jon

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://docs.xcp-ng.org/project/contributing/#developer-certificate-of-origin-dco

2024-11-04 15:10 UTC, stormi commented on docs/storage/storage.md
> +    <td>X</td>
Note: it's supported in XCP-ng 8.2, not in XCP-ng 8.3 yet.

2024-11-05 03:42 UTC, Danp2 commented
Isn't `fibre channel` already covered by `hba`?

2024-11-05 10:42 UTC, stormi commented
> Isn't `fibre channel` already covered by `hba`?

I thought so, but @Fohdeesha said that an entry is missing for Fibre Channel and my knowledge of HBA and FC is so limited that I didn't object.

2024-11-05 10:51 UTC, Fohdeesha commented
@Danp2 HBA and fibrechannel are two very different SR types/storages, HBA is plain HBAs presenting SAS connections with no networking possible, fibrechannel is LVM over actual fibrechannel networks. We've already had one customer asking why we don't support FC because they couldn't find it in the feature matrix this PR is covering

2024-11-05 10:52 UTC, Fohdeesha approved these changes
looks good!

2024-11-06 10:49 UTC, stormi approved these changes
Good for me if the need is urgent, else I'd wait for an additional commit adding the missing Fibre Channel section in the page.

2026-06-20 21:47 UTC, stormi commented
@thomas-dkmt The last comment was adressed to you.

2026-06-22 21:08 UTC, stormi requested changes
Changing my review to "changes requested" so that the PR is clearly identified as requiring an action from the author.

2026-07-09 11:32 UTC, thomas-dkmt commented on docs/storage/storage.md
> +    <td>X</td>
Added mention of XCP-ng 8.2 support

2026-07-10 05:42 UTC, Fohdeesha commented on docs/storage/storage.md
> +    <td>X</td>
@stormi hmm? FC has been supported since day 1 in 8.3, it's the regular HBA type - they just show up as regular block devices. This is proper FC where an HBA hardware card handles the FC layer stuff and presents native block devices to the OS, not FCoE which requires software daemon conversion crap in dom0 (and was deprecated by citrix years ago iirc). We have many many customers using FC shared storage in 8.3

2026-07-10 16:57 UTC, stormi commented on docs/storage/storage.md
> +    <td>X</td>
This comment was about XOSTOR, not FC. But this PR is so old now that it isn't true anymore. It's well supported in XCP-ng 8.3 now.

2026-07-10 17:02 UTC, stormi commented on docs/storage/storage.md
> +    <td>X</td>
@thomas-dkmt I know that I asked for this change, but this was in November, 2024. You know that XOSTOR is supported in XCP-ng 8.3 now, since mid 2025.

2026-07-10 19:27 UTC, Wescoeur approved these changes
It's ok for me (except for the XOSTOR issue raised by Samuel).

2026-07-15 06:58 UTC, thomas-dkmt commented on docs/storage/storage.md
> +    <td>X</td>
Sorry and thanks for the reminder. Fixed.

2026-07-22 12:35 UTC, Wescoeur approved these changes

2026-08-04 12:31 UTC, stormi approved these changes

2026-08-04 12:32 UTC, stormi commented
@Fohdeesha good for you?

2026-08-04 13:20 UTC, Fohdeesha approved these changes

2026-08-04 13:20 UTC, Fohdeesha commented
@stormi very good

2026-08-04 13:44 UTC, merged