[WIP] Vdi io path
xcp-ng/xcp-ng-org pull request #59
Opened 2020-12-09 12:46 UTC by Wescoeur

@beshleman Can you check if the grammar is correct please? This branch is directly connected to https://github.com/xcp-ng/xcp-ng-org/pull/49, so can you approve or comment in the previous PR? When you have time. :wink: 

@Nambrok You can complete this PR if you have things or improvements to add in the doc. :slightly_smiling_face:

2020-12-09 23:41 UTC, beshleman requested changes

2020-12-09 23:41 UTC, beshleman commented on docs/architecture.md
> +4. In tapdisk when the event channel is notified, the request is read and the guest segments are copied into a local buffer using `iocl` with a `IOCTL_GNTDEV_GRANT_COPY` request. So before writing to
~~iocl~~ ioctl

we must ~~have to~~ make a copy

2020-12-10 10:47 UTC, Wescoeur commented on docs/architecture.md
> +XenStore is a centralized database residing on `Dom0`, it is accessible using a `UNIX socket` or with `XenBus` + `ioctl`. It's also a hierarchical namespace allowing to read/write, enumerate a virtua
I will use your last suggestion. :wink: But:
> I would change "allowing to" to "allowing to"

What did you mean? :sweat_smile:

2020-12-10 10:49 UTC, Wescoeur commented on docs/architecture.md
> +A PV driver can interact with the `XenStore` to get or set configuration, it's not used for large data exchanges. The store is mainly used during PV driver negociation via `XenBus`.
:+1: When the french word "négociation" is really close to its English translation... :sweat_smile:

2020-12-11 03:56 UTC, beshleman commented on docs/architecture.md
> +XenStore is a centralized database residing on `Dom0`, it is accessible using a `UNIX socket` or with `XenBus` + `ioctl`. It's also a hierarchical namespace allowing to read/write, enumerate a virtua
Lol!  I fixed my comment, my syntax rendered into bad html haha

2020-12-11 03:58 UTC, beshleman commented on docs/architecture.md
> +A PV driver can interact with the `XenStore` to get or set configuration, it's not used for large data exchanges. The store is mainly used during PV driver negociation via `XenBus`.
I figured!

2021-02-22 17:46 UTC, olivierlambert commented
What should we do with this PR? @Wescoeur what's left to merge it?

2021-02-24 13:57 UTC, merged